openapi: 3.0.0
info:
  title: NodeJS Boilerplate
  description: Sample project to be used as start point for NodeJS applications
  version: 1.0.0
servers:
  - url: http://HOST_IP:HOST_PORT/api
    description: Service API URI

paths:
  /:
    get:
      summary: Default URL indicating that server is up
      responses:
        '200':
          description: Response from server
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    description: Message from server
                